# Generated by Django 5.2.8 on 2025-11-29 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("PL", "Playing"), ("GO", "Game Over"), ("WI", "Win")],
                        default="PL",
                        max_length=2,
                    ),
                ),
                ("width", models.SmallIntegerField()),
                ("height", models.SmallIntegerField()),
                ("mines", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coord_x", models.SmallIntegerField()),
                ("coord_y", models.SmallIntegerField()),
                ("mined", models.BooleanField()),
                ("opened", models.BooleanField()),
                ("flagged", models.BooleanField()),
                ("danger_neighbours", models.SmallIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
            ],
        ),
    ]
